### ISSUE TITLE
Content of the Help section in Course lesson module is missing

### ISSUE THREAD

**Issue by wisharya** [frappe/school#256]
@pateljannat, There is a help section which is there to guide like how to add videos embedded in the lesson. The content of that section is missing.

![Screenshot_20211102-110228_Firefox](https://user-images.githubusercontent.com/25725389/139791792-edfd465d-c095-4832-9b5e-3a49e81315a5.png)

**Comment by pateljannat** [comment]
@wisharya This has been fixed recently. Update the site to the latest version.

**Comment by wisharya** [comment]
Hey, the latest update is throwing the following error:
`Migrating echolearn.frappe.cloud `
`Could not find app "community"`
![Screenshot 2021-11-02 at 11-52-51 Frappe Cloud](https://user-images.githubusercontent.com/25725389/139796398-71ffecdb-ebc6-4aee-8ab7-78e68d81a69f.png)

**Comment by wisharya** [comment]
Also, I find the format to add non-youtube videos - {{ Video("https://vimeo.com/640436924") }}
It is throwing the following error:

![Screenshot](https://user-images.githubusercontent.com/25725389/139796912-6c96d492-b8d8-4e40-85d5-5034c08a5920.png)
.

**Comment by pateljannat** [comment]
Looking into it

**Comment by pateljannat** [comment]
@wisharya The migration issue and help section issue are resolved. Checking the video issue now.

**Comment by wisharya** [comment]
> @wisharya The migration issue and help section issue are resolved. Checking the video issue now.

Thanks.

**Comment by pateljannat** [comment]
@wisharya regarding the video issue. The {{ Video }} markdown uses the video tag of HTML. Video tag only supports videos of the format mp4, WebM, or Ogg. Since you are using videos from Vimeo the URL won't be sufficient. 

To add these videos to lessons, go to the video page on Vimeo. Click on the share icon. You will see a section called embed. There you will find an iframe. Copy the iframe and paste it into the lesson. This would render the video in the lesson.

**Comment by wisharya** [comment]
Thanks. I'll look into this and will get back to you.

**Comment by wisharya** [comment]
It works. Thanks!
